<a href="https://colab.research.google.com/github/Owen150/AI-ML-Group-Task/blob/main/Practice1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [21]:
import pandas as pd #dataset library
import numpy as np #linear algebra library


In [47]:
from numpy import array
from sklearn.preprocessing import Normalizer
from keras.activations import sigmoid
from keras.losses import mse

Hyperparameters

In [43]:
batch_size = 2 #2 rows result

In [23]:
data_dict = {'Day 1':[30,40,50,20,15,60], 'Day 2':[40,50,20,15,60,70],
             'Day 3':[50,20,15,60,70,50], 'Target':[20,15,60,70,50,40]}

In [24]:
data = pd.DataFrame(data_dict)

In [25]:
data

Day 1  Day 2  Day 3  Target
0     30     40     50      20
1     40     50     20      15
2     50     20     15      60
3     20     15     60      70
4     15     60     70      50
5     60     70     50      40

In [26]:
X = data.drop('Target', axis = 1)
Y = data['Target']

In [27]:
X_trans = Normalizer(norm='max').fit_transform(X)

In [28]:
np.reshape(array(Y), (1,-1))

array([[20, 15, 60, 70, 50, 40]])

In [29]:
Y = Normalizer(norm='max').fit_transform(np.reshape(array(Y),(1,-1)))

In [30]:
Y

array([[0.28571429, 0.21428571, 0.85714286, 1.        , 0.71428571,
        0.57142857]])

In [31]:
X_trans

array([[0.6       , 0.8       , 1.        ],
       [0.8       , 1.        , 0.4       ],
       [1.        , 0.4       , 0.3       ],
       [0.33333333, 0.25      , 1.        ],
       [0.21428571, 0.85714286, 1.        ],
       [0.85714286, 1.        , 0.71428571]])

In [32]:
Normalizer().fit_transform(data)

array([[0.40824829, 0.54433105, 0.68041382, 0.27216553],
       [0.58191437, 0.72739297, 0.29095719, 0.21821789],
       [0.60971076, 0.2438843 , 0.18291323, 0.73165291],
       [0.20936957, 0.15702718, 0.62810871, 0.73279349],
       [0.14157875, 0.56631501, 0.66070085, 0.47192918],
       [0.53452248, 0.62360956, 0.4454354 , 0.35634832]])

ANN Model

In [34]:
weight_1 = array([[.2,.1],[.3,.1],[.2,.1]])
weight_2 = array([[.5],[.1]])

In [35]:
X = X_trans

In [44]:
output_1 = X[0:batch_size]@weight_1
output_1

array([[0.56, 0.24],
       [0.54, 0.22]])

In [45]:
act_output_1 = sigmoid(output_1).numpy()
act_output_1

array([[0.63645254, 0.55971365],
       [0.63181242, 0.55477924]])

In [46]:
final_output = act_output_1@weight_2
final_output

array([[0.37419764],
       [0.37138413]])

In [53]:
Y_true = Y[0][0:batch_size]
Y_pred = final_output.T[0]

In [49]:
Y_true

array([0.28571429, 0.21428571])

In [54]:
Y_pred.T

array([0.37419764, 0.37138413])

Computing Mean Squared Error

In [55]:
mse(Y_true,Y_pred).numpy()

0.016254608040052337